# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: percona
    environment:
        - MYSQL_ROOT_PASSWORD=jF4#vC*VKpM5xt#)eu#
    volumes:
       - /root/percona/my.cnf:/etc/my.cnf
       - /root/percona/data:/var/lib/mysql        
  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080
