# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    image: percona
    environment:
        - MYSQL_ROOT_PASSWORD=secret
    volumes:
       - /percona_mysql/my.cnf:/etc/my.cnf
       - /percona_mysql/data:/var/lib/mysql        
  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080
